github.com:
    users:
        Akashdip1:
            oauth_token: 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
    git_protocol: https
    user: Akashdip1
    oauth_token: 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
