github.com:
    users:
        Akashdip1:
            oauth_token: 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
    git_protocol: https
    user: Akashdip1
    oauth_token: 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
